######################## default configuration ####################
baseURL = "https://cornelltsa.github.io"
title = "Cornell TSA 康乃爾臺灣同學會"
theme = "port-hugo"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/hugrid.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#home"
weight = 1

[[menu.main]]
name = "About Us"
URL = "#about"
weight = 2

[[menu.main]]
name = "Previous Events"
URL = "#portfolio"
weight = 3


#################### default parameters ################################
[params]
copyright = "Copyright Cornell Taiwanese Student Association &copy;"
# Meta data
description = "The Cornell Taiwanese Student Association (CTSA; 康乃爾臺灣同學會) is a group aimed at helping Taiwanese students adapt to life and academic studies within the Cornell community."
author = "Zong-Yan Liu"
favicon = "images/icons/logo.png"
google_analytics = "G-LY2EL8WKZ3"


# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

############################# social site ########################

[[params.social]]
icon = "fas fa-envelope" 
link = "mailto:cornell.ctsa@gmail.com"

[[params.social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/groups/cornelltsa/"

contentDir = "content/english"
weight = 1
home = "Home"
